name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/knowledge-intelligence-platform
            git pull
            cd backend
            source venv/bin/activate
            pip install -r requirements.txt
            sudo supervisorctl restart synapse